
app_name: 'testModule'
project_name: 'testProject'
project_version: '0.1'

logging:
  level: DEBUG
  format: '%(levelname)s %(asctime)s  %(message)s'
  message_format: '%(project_name)s:%(project_version)s %(app_id)s %(_filename)s:%(_lineno)d [%(tags)s] '

  filters:
    trans:
      tag: 'TRANS:'   # tag 过滤
  handlers:
    - type: file
      enable: true
      filename: 'server.log'
      encoding: 'UTF-8'
      max_bytes: 67108864 # 64MB
      backup_count: 10

    - type: console
      enable: true



http_trace: #自动日志记录
  level: DEBUG
  request:
    options:
      header:  false
      body:  true
      max_size: 500 # 最大数据包长度
    urls:
      - match: '/'
      - match: 'zoo/cat'
        body:  true

  response:
    options:
      header:  false
      body:  true
      max_size: 500 # 最大数据包长度
    urls:
      - match: '/'
      - match: 'zoo/cat'
        body:  true



datasources:
  - name: 'mongodb'
    class: 'mantis.fundamental.nosql.mongo.Datasource'
    host: 'mongodb'
    port: 27017
    dbname:
    user:
    password:
    enable: true

  - name: 'zk_1'
    type: 'zookeeper'
    enable: false
    hosts: 'localhost:2181'
    root: '/camel'

  - name: 'redis'
    class: 'mantis.fundamental.redis.datasource.Datasource'
    host: 'redis'
    port: 6379
    password: ''
    db: 0
    enable: true

message_brokers:
  - name: 'kafka_1'
    class: 'mantis.fundamental.kafka.MessageBroker'
    enable: false
    hosts: 'localhost:9092'
    zookeepers: 'localhost:2181'
    channels:
      - name: 'test'
        group: 'abcdef'  # simple_consumer if group is null
        handler:  'access.kafka.test.get_message' # last unit< get_message> is function object
        enable: true
        type: 'queue'

  - name: 'redis'
    class: 'mantis.fundamental.redis.broker.MessageBroker'
    host: 'redis'
    port: 6379
    password: ''
    db: 0
    enable: true
    channels:
      - name: 'ctp_contract_tick_queue'
#        handler: 'get_message'
        enable: true
        type: 'queue' # or queue

services:
  - name: 'http'
    class: 'mantis.fundamental.flask.service.FlaskService'
    enable: true
    block: false
    cfgs:
      SQLALCHEMY_DATABASE_URI : 'sqlite:////tmp/test.db'
      SQLALCHEMY_BINDS:
      SQLALCHEMY_TRACK_MODIFICATIONS : true
      SQLALCHEMY_COMMIT_ON_TEARDOWN : true
      SECRET_KEY : "abc"
      TEMPLATES_AUTO_RELOAD: true
      DEBUG: true
      SEND_FILE_MAX_AGE_DEFAULT: 0
    http:
#      host : '172.16.109.237'
      host : '127.0.0.1'
      port : 25100
      threaded: false
      debug: true
      websocket: false

    blueprints:
      - package: 'http'
        url: '/'
        name: 'http'
        register: true
        modules:
          - name: 'views'
            url: 'console'
            routes:
              - url: '/'                    # url name
                name: 'index'   # function name
                methods: 'GET'
              - url: '/orders'                    # url name
                name: 'orders'   # function name
                methods: 'GET'
          - name: 'api'
            url: 'api/m/bw/dev'
            routes:
              - url: '/ticket'           # 用户微信登录
                name: 'get_ticket'       #
                methods: 'POST,GET'

              - url: '/user'           # 用户微信登录
                name: 'get_user_info'       #
                methods: 'GET'

              - url: '/user'           # 用户微信登录
                name: 'update_user_info'       #
                methods: 'PUT'

              - url: '/wx/user'           # 微信用户信息
                name: 'update_wxuser_info'       #
                methods: 'POST'

              - url: '/wx/user'           # 微信用户信息
                name: 'get_wxuser_info'       #
                methods: 'GET'

              - url: '/wx/system'           # 微信系统信息
                name: 'update_wxsystem_info'       #
                methods: 'POST'

              - url: '/device'        # 用户添加设备
                name: 'add_device'
                methods: 'POST'

              - url: '/device/password'           # 设备密码找回
                name: 'get_device_password'       #
                methods: 'POST'

              - url: '/device'          # 更新设备信息
                name: 'update_device'
                methods: 'PUT'

              - url: '/device'        # 删除设备
                name: 'remove_device'
                methods: 'DELETE'

              - url: '/device'            # 获取设备详情
                name: 'get_device_info'
                methods: 'GET'



              - url: '/device/list'            # 获取设备列表详情
                name: 'get_device_list'
                methods: 'GET'

              - url: '/share-device'            # 创建共享设备
                name: 'create_share_device'
                methods: 'POST'
              - url: '/share-device'            # 创建共享设备
                name: 'update_share_device'
                methods: 'PUT'

              - url: '/share-device'            # 删除共享设备
                name: 'remove_share_device'
                methods: 'DELETE'

              - url: '/share-device/take'            # 用户添加共享设备
                name: 'take_share_device'
                methods: 'POST'

              - url: '/share-device'            # 用户查询共享设备
                name: 'get_device_share_info'
                methods: 'GET'

              - url: '/share-device/code'            # 生成分享码
                name: 'create_share_device_code'
                methods: 'POST'

              - url: '/share-device/list'            # 用户查询共享设备
                name: 'get_share_device_list'
                methods: 'GET'

#              - url: '/share-device/follower'            # 共享设备的访问用户信息
#                name: 'get_share_device_access_user'
#                methods: 'GET'

              - url: '/share-device/follower/list'
                name: 'get_share_device_follower_list'       # 查询指定共享设备关联的所有访问用户记录
                methods: 'GET'

              - url: '/share-device/follower/allow'
                name: 'share_device_follower_allow'       # 查询指定共享设备关联的所有访问用户记录
                methods: 'POST'

              - url: '/share-device/follower/deny'
                name: 'share_device_follower_deny'       # 查询指定共享设备关联的所有访问用户记录
                methods: 'POST'

              - url: '/device/pos/last'            # 用户查询位置信息
                name: 'get_last_position'
                methods: 'GET'

              - url: '/device/pos/last/multi'            # 用户查询位置信息
                name: 'get_last_position_multi'
                methods: 'GET'

              - url: '/device/pos/trace'            # 用户查询共享设备
                name: 'get_position_path'
                methods: 'GET'

              - url: '/device/pos/trace/multi'            # 用户查询共享设备
                name: 'get_position_path_multi'
                methods: 'GET'

              - url: '/device/config'            # 用户查询设备配置信息
                name: 'get_device_config'
                methods: 'GET'

              - url: '/device/config'            # 用户设置设备配置信息
                name: 'set_device_config'
                methods: 'PUT'

              - url: '/device/fence'            # 用户设置设备配置信息
                name: 'get_device_fence'
                methods: 'GET'

              - url: '/device/fence'            # 用户设置围栏信息
                name: 'set_device_fence'
                methods: 'PUT'

              - url: '/command/audio/start'            # 用户设置设备配置信息
                name: 'cmd_start_audio_record'
                methods: 'POST'

              - url: '/command/audio/listen'            # 设备监听
                name: 'cmd_start_audio_listen'
                methods: 'POST'

              - url: '/command/position-now-gps'            # 用户设置设备配置信息
                name: 'cmd_position_now_gps'
                methods: 'GET,POST'

              - url: '/command/position-now-lbs'            # 用户设置设备配置信息
                name: 'cmd_position_now_lbs'
                methods: 'GET,POST'

              - url: '/command/position-now'            # 用户设置设备配置信息
                name: 'cmd_position_now'
                methods: 'GET,POST'

              - url: '/command/shutdown'            # 用户设置设备配置信息
                name: 'cmd_shutdown'
                methods: 'GET,POST'

              - url: '/command/reboot'            # 用户设置设备配置信息
                name: 'cmd_reboot'
                methods: 'GET,POST'

              - url: '/audio/list'            #
                name: 'get_audio_record_list'
                methods: 'GET'

              - url: '/audio'            #  /audio/?audio_id=1123123123
                name: 'get_audio_content'
                methods: 'GET'

              - url: '/device/view/top'            #  设备置顶
                name: 'set_view_device_top'
                methods: 'POST'

              - url: '/favorite'            #  添加收藏
                name: 'create_favorite'
                methods: 'POST'

              - url: '/favorite/list'            #  添加收藏
                name: 'get_favorite_list'
                methods: 'GET'

              - url: '/favorite'            #  添加收藏
                name: 'get_favorite'
                methods: 'GET'

              - url: '/favorite'            #  添加收藏
                name: 'remove_favorite'
                methods: 'DELETE'

              - url: '/cargo-address'            #  添加收藏
                name: 'create_cargo_address'
                methods: 'POST'

              - url: '/cargo-address/list'            #  添加收藏
                name: 'get_cargo_address_list'
                methods: 'GET'

              - url: '/cargo-address'            #  添加收藏
                name: 'get_cargo_address'
                methods: 'GET'

              - url: '/cargo-address'            #  添加收藏
                name: 'update_cargo_address'
                methods: 'PUT'

              - url: '/cargo-address'            #  添加收藏
                name: 'remove_cargo_address'
                methods: 'DELETE'

          - name: 'product'
            url: 'api/m/bw/dev/product'
            routes:
              - url: '/list'            #  添加收藏
                name: 'get_product_list'
                methods: 'GET'

              - url: '/'            #  添加收藏
                name: 'get_product'
                methods: 'GET'

          - name: 'group'
            url: 'api/m/bw/dev/group'
            routes:
              - url: '/list'            #  添加收藏
                name: 'get_group_list'
                methods: 'GET'
              - url: ''            #  添加收藏
                name: 'get_group_info'
                methods: 'GET'

              - url: ''            #  添加收藏
                name: 'create_group'
                methods: 'POST'

              - url: ''            #  添加收藏
                name: 'update_group_info'
                methods: 'PUT'

              - url: ''            #  添加收藏
                name: 'remove_group'
                methods: 'DELETE'

              - url: '/device'            #  添加收藏
                name: 'add_device_into_group'
                methods: 'POST'

              - url: '/device'            #  删除组设备
                name: 'remove_device_from_group'
                methods: 'DELETE'


  - name:       'main'
    id:     'location-adapter'
    enable:     true
    class:      'main.MainService'

    fanout:
      - name: 'switch0'
        channels:
#          - 'redis/con/queue'
          - 'redis/concox_device_message/pubsub'
      - name: 'logging'
        channels:
          - 'redis/trade.log.{service_type}/queue'
          - 'redis/trade.log.{service_type}.{service_id}/pubsub'
      - name: 'strategy_logging'
        channels:
          - 'redis/trade.strategy.log/queue'
          - 'redis/trade.strategy.log.pub/pubsub'

    command_controllers:
      - name: 'gt03'
        class: 'mantis.BlueEarth.vendor.concox.gt03.command.CommandController'
      - name: 'gt310'
        class: 'mantis.BlueEarth.vendor.concox.gt310.command.CommandController'
      - name: 'ev25'
        class: 'mantis.BlueEarth.vendor.concox.ev25.command.CommandController'

    location_server_api_command: 'http://localhost:19002/api/command'
    wx_settings:
      position_pull_interval: 5

    max_position_request_interval: 10 # 发送立即定位命令的最大时间间隔
    wx_settings:
      code2session_url : 'https://api.weixin.qq.com/sns/jscode2session'
      appid : 'wx2f96932f02f10eb7'
      secret: '1408035115428654d169e7d1063654ec'

    sms:
      ak: "LTAI29n3aEgO7zCs"
      secret: "B03v23yB2kNURukVj3txBg6QutzO4q"
      signatures:
        shyg: '上海晏归'
      templates:
        user_verify: 'SMS_146745088'  # 验证码
        find_device_password: 'SMS_146745088' # 找回设备密码
#    static_root_url: 'http://localhost:25100/static'
    static_root_url: 'https://wx.wallizard.com/static'




# qpid-receive -b localhost:5672 -a "mq_test;{create:always,node:{type:queue,durable:true}}"






